spring:
    datasource:
        url: jdbc:mysql://localhost:3306/attendance?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
        username: root
        password: root
        #type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.jdbc.Driver
            initial-size: 5
            min-idle: 5
            max-active: 20
            max-wait: 60000
            validation-query: select 1
            validation-query-timeout: 1
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 600000
            pool-prepared-statements: false
            max-pool-prepared-statement-per-connection-size: -1
            use-global-data-source-stat: true
            filter:
                stat:
                    db-type: mysql
                    log-slow-sql: true
                    slow-sql-millis: 2000
                wall:
                    enabled: true
                    db-type: mysql
                    config:
                        delete-allow: true
                        update-allow: true
                        insert-allow: true
                        select-into-allow: false
                        create-table-allow: false
                        alter-table-allow: false
                        drop-table-allow: false
                        merge-allow: false
                        truncate-allow: false
                        none-base-statement-allow: false
                        multi-statement-allow: false
                        use-allow: false
                        describe-allow: false
    # database: Redis数据库索引（默认为0）
    # timeout: 连接超时时间（毫秒）
    # min-idle: 连接池中的最小空闲连接
    # max-idle: 连接池中的最大空闲连接
    # max-wait-millis: 连接池最大阻塞等待时间（使用负值表示没有限制）
    redis:
        host: 127.0.0.1
        port: 6379
        password: null
        database: 0
        jedis:
            pool:
                min-idle: 0
                max-idle: 8
                max-total: 16
                max-wait-millis: -1
    session:
        store-type: none
    mvc:
        favicon:
            enabled: false
        view:
            prefix: /jsp/
            suffix: .jsp
        static-path-pattern: /resources/**
    resources:
        static-locations: /resources/
    thymeleaf:
        cache: false
        enabled: false
mybatis:
    mapper-locations: classpath:/com/madder/attendance/dao/mapper/*.xml
    type-aliases-package: com.madder.attendance.bean
    configLocation: classpath:mybatis/mybatis-config.xml